# Reference
# https://www.elastic.co/guide/en/kibana/current/settings.html

# Kibana-specific settings
server:
  host: "0.0.0.0"

# Kibana-to-Elasticsearch communication
elasticsearch:
  hosts: [ "https://elasticsearch:9200" ]
  ssl:
    certificateAuthorities: config/ca.crt
    certificate: config/certs/kibana.crt
    key: config/certs/kibana.key
  username: "kibana_system"
  password: "kibana"